workflows:
  e2e-ios:
    scripts:
      # .github/workflows/scripts/install-tools.sh
      - flutter config --no-analytics
      - flutter pub global activate melos 2.4.0
      - flutter pub global activate flutter_plugin_tools
    environment:
      flutter: stable
      node: 16
      java: 11
