defaults:
  environment: &e2e_env
    flutter: stable
    node: 16
    java: 11


workflows:
  e2e-android:
    instance_type: linux_x2
    scripts:
      - echo 123
    environment:
      <<: *e2e_env

  e2e-ios:
    max_build_duration: 15
    scripts:
      - name: Install tools
        script: |
          set -e
          flutter config --no-analytics
          flutter pub global activate melos 2.4.0
          flutter pub global activate flutter_plugin_tools
          sudo npm add --global firebase-tools
      - name: Build application
        working_directory: tests
        script: |
          flutter build ios --no-codesign --simulator --debug --target=./integration_test/e2e_test.dart --dart-define=CI=true
      - name: Build Firebase Cloud Functions
        working_directory: ./.github/workflows/scripts/functions
        script: |
          npm ci --no-audit
      - name: Ensure iPhone simulator
        script: |
          set -e
          xcrun simctl bootstatus "${DEVICE_ID?}" -b
          xcrun simctl logverbose "${DEVICE_ID?}" enable
      - name: Run E2E tests
        working_directory: ./.github/workflows/scripts
        script: |
          firebase emulators:exec --only auth,firestore,functions,storage,database --project flutterfire-e2e-tests \
            "cd $CM_BUILD_DIR/tests && flutter test integration_test/e2e_test.dart -d \"${DEVICE_ID?}\" --dart-define=CI=true"
    environment:
      <<: *e2e_env
      vars:
        DEVICE_ID: "iPhone 11"
    cache:
      cache_paths:
        - $HOME/.cache/firebase/emulators
