workflows:
  e2e-ios:
    scripts:
      # .github/workflows/scripts/install-tools.sh
      - flutter config --no-analytics
      - flutter pub global activate melos 2.4.0
      - flutter pub global activate flutter_plugin_tools
      - sudo npm i -g firebase-tools
      - name: Build application
        working_directory: tests
        script: |
          flutter build ios --no-codesign --simulator --debug --target=./integration_test/e2e_test.dart --dart-define=CI=true
    environment:
      flutter: stable
      node: 16
      java: 11
