defaults:
  - environment: &e2e_tests
      flutter: stable
      node: 16
      java: 11


workflows:
  e2e-android:
    instance_type: linux_x2
    max_build_duration: 15
    scripts:
      - name: Install tools
        script: |
          set -e
          flutter config --no-analytics
          flutter pub global activate melos 2.4.0
          flutter pub global activate flutter_plugin_tools
          flutter config --no-enable-web --no-enable-ios --no-enable-macos-desktop
          sudo npm add --global firebase-tools
      - name: Build Android application
        working_directory: tests
        script: |
          flutter build apk --debug --target=./integration_test/e2e_test.dart --dart-define=CI=true --no-android-gradle-daemon
      - name: Build Firebase Cloud Functions
        working_directory: ./.github/workflows/scripts/functions
        script: |
          npm ci --no-audit
      - name: Ensure Android emulator
        script: |
          set -e
          adb start-server
          flutter emulators --launch emulator &
          adb logcat '*:D' > $HOME/adb-log.txt &
          adb wait-for-device
      - name: Run E2E tests
        working_directory: ./.github/workflows/scripts
        script: |
          firebase emulators:exec --only auth,firestore,functions,storage,database --project flutterfire-e2e-tests \
            "cd $CM_BUILD_DIR/tests && flutter test integration_test/e2e_test.dart --dart-define=CI=true"
    artifacts:
      - $HOME/adb-log.txt
    environment:
      <<: *e2e_tests

  e2e-ios:
    max_build_duration: 15
    scripts:
      - name: Install tools
        script: |
          set -e
          flutter config --no-analytics
          flutter pub global activate melos 2.4.0
          flutter pub global activate flutter_plugin_tools
          sudo npm add --global firebase-tools
      - name: Build iOS application
        working_directory: tests
        script: |
          flutter build ios --no-codesign --simulator --debug --target=./integration_test/e2e_test.dart --dart-define=CI=true
      - name: Build Firebase Cloud Functions
        working_directory: ./.github/workflows/scripts/functions
        script: |
          npm ci --no-audit
      - name: Ensure iPhone simulator
        script: |
          set -e
          xcrun simctl bootstatus "${DEVICE_ID?}" -b
          xcrun simctl logverbose "${DEVICE_ID?}" enable
      - name: Run E2E tests
        working_directory: ./.github/workflows/scripts
        script: |
          firebase emulators:exec --only auth,firestore,functions,storage,database --project flutterfire-e2e-tests \
            "cd $CM_BUILD_DIR/tests && flutter test integration_test/e2e_test.dart -d \"${DEVICE_ID?}\" --dart-define=CI=true"
    environment:
      <<: *e2e_tests
      vars:
        DEVICE_ID: "iPhone 11"

  e2e-macos:
    instance_type: mac_pro
    scripts:
      - name: Install tools
        script: |
          set -e
          flutter config --no-analytics
          flutter pub global activate melos 2.4.0
          flutter pub global activate flutter_plugin_tools
          sudo npm add --global firebase-tools
      - name: Build macOS application
        working_directory: tests
        script: |
          flutter build macos --debug --target=./integration_test/e2e_test.dart --device-id=macos --dart-define=CI=true
      - name: Build Firebase Cloud Functions
        working_directory: ./.github/workflows/scripts/functions
        script: |
          npm ci --no-audit
      - name: Run E2E tests
        working_directory: ./.github/workflows/scripts
        script: |
          firebase emulators:exec --only auth,firestore,functions,storage,database --project flutterfire-e2e-tests \
            "cd $CM_BUILD_DIR/tests && flutter test integration_test/e2e_test.dart -d macos --dart-define=CI=true"
    environment:
      <<: *e2e_tests
      xcode: 13.2   # macOS 11
